version: "2"
services:
  app:
    build: ./
    volumes:
      - ./app:/app
      - ${CSV_PATH}:/app/data/csvin.csv
    environment:
      - NEW_CURRENCY_MULTIPLIER=${NEW_CURRENCY_MULTIPLIER}
      - NEW_CURRENCY_CODE=${NEW_CURRENCY_CODE}
      - CSV_PATH=${CSV_PATH}
